### ISSUE TITLE
Create "advanced" versions of the C/C++ binaries with extra effort to hide things

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets-binaries#11]
- [x] Add "__attribute__((visibility("hidden")));"  to methods (See https://stackoverflow.com/questions/2872638/how-to-remove-strings-from-a-compiled-binary-so)
- [x] use strip -g to remove symbols and such
- [x] only work with arrays of characters, remove the answer as a string
- [x] have the array of chars encrypted and/or encoded with a hardcoded key
- [x] extend the github actions to generate downloads for this version.

**Comment by roddas** [comment]
I'm working on it.

**Comment by commjoen** [comment]
symbol removal is being tested by stacksmashing \o/
