### ISSUE TITLE
Create automated builds and cross compilations for each folder

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets-binaries#19]
Create automated builds and cross compilations for each folder with github actions (so that github can do our `quickbuild.sh` 😉 ):
- [x] C
- [x] C++
- [x] Rust
- [x] Golang

Next,
add badges for each job to readme:
- [x] C
- [x] C++
- [x] Rust
- [x] Golang

**Comment by puneeth072003** [comment]
Happy to help ❤️

**Comment by puneeth072003** [comment]
@commjoen Is this completed?
I'm really sorry for the delay.
🥹

**Comment by commjoen** [comment]
All good @puneeth072003 . Can you complete the rust part please :-)? That would be awesome!

**Comment by puneeth072003** [comment]
Sure🤓

**Comment by commjoen** [comment]
Thank you @puneeth072003 ! Closing this one now.
