### ISSUE TITLE
Fix binaries for windows

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets-binaries#8]
- [ ] the Cplus cross compilation fails: output in exe is not there
- [x] the golang lib shows all kind of weird symbols if you call it

**Comment by davevs** [comment]
screenshots:
cplus
![image](https://user-images.githubusercontent.com/18188237/212323136-a70a9841-d504-4e77-9a11-8eb1b405e8a0.png)

golang
![image](https://user-images.githubusercontent.com/18188237/212323202-b82c904e-ab23-4e59-b53e-585350be5054.png)

**Comment by commjoen** [comment]
submitted the new golang and cplus binary for testing ^^
